default: &default
  adapter: postgresql
  encoding: unicode
  username: icl
  password: icl
  pool: 5

development:
  <<: *default
  database: ICL_development

test:
  <<: *default
  database: ICL_test

production:
  <<: *default
  database: ICL_production
